export { default as Home } from './Home.vue'
export { default as Login } from './Login.vue'
export { default as Register } from './Register.vue'

export { default as Dashboard } from './App/Dashboard.vue'
export { default as Categories } from './App/Categories.vue'
export { default as NotFound } from './404.vue'
export { default as RegistrationSuccess } from './RegistrationSuccess.vue'
export { default as VerificationStatus } from './VerificationStatus.vue'
export { default as ForgotPassword } from './ForgotPassword.vue'
export { default as ForgotPasswordSuccess } from './ForgotPasswordSuccess.vue'
export { default as ResetPassword } from './ResetPassword.vue'
export { default as ErrorPage } from './ErrorPage.vue'
export { default as ResetSuccess } from './ResetSuccess.vue'
export { default as VerificationSuccess } from './VerificationSuccess.vue'
export { default as VerificationFailed } from './VerificationFailed.vue'
export { default as ResendSuccess } from './ResendSuccess.vue'
